version: "3.7"
services:
    api:
        container_name: api
        build:
            context: api/docker/development/nginx
        ports:
            - "8080:80"
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm
    api-php-fpm:
        container_name: api-php-fpm
        build: 
            context: api/docker/development/php-fpm
        volumes: 
            - ./api:/app
        environment:
            APP_DEBUG: 1
    api-php-cli:
        container_name: api-php-cli
        build:
            context: api/docker/development/php-cli
        volumes:
            - ./api:/app
        environment:
            APP_DEBUG: 1
    