version: "3.7"
services:
    api:
        container_name: api
        build:
            context: docker/development/nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/app
        depends_on:
            - api-php-fpm
    api-php-fpm:
        container_name: api-php-fpm
        build: 
            context: docker/development/php-fpm
        volumes: 
            - ./:/app
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
            PHP_IDE_CONFIG: serverName=app
            DB_URL: pgsql://app:secret@api-postgres:5432/app
    api-php-cli:
        container_name: api-php-cli
        build:
            context: docker/development/php-cli
        volumes:
            - ./:/app
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
            DB_URL: pgsql://app:secret@api-postgres:5432/app
        tty: true
    api-postrgres:
        container_name: api-postgres
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    api-postgres:
